import {
  Component,
  OnInit
} from '@angular/core';

@Component({
  selector: 'app-portfolio',
  templateUrl: './portfolio.component.html',
  styleUrls: ['./portfolio.component.css']
})
export class PortfolioComponent implements OnInit {
  portfolioParts = [{

      name: 'Styling area',
      class: 'styling',
      subtitle: 'daily practice',
      footerContent: 'browsing all in github',
      areaProjects: [{
          projectImg: 'assets/img/projects/mainMenu.gif',
          projectTitle: 'main Menu (Codepen Challenge)',
          projectSkills: 'HTML5, CSS3, SASS/SCSS',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'https://codepen.io/Mohamed-Ayman/full/WyYGPa',
          projectSource: 'https://codepen.io/Mohamed-Ayman/pen/WyYGPa',
          projectTime: '2018',
        },
        {
          projectImg: 'assets/img/projects/memoryGame.gif',
          projectTitle: 'Memory Game',
          projectSkills: 'HTML5, CSS3, SASS/SCSS',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'https://codepen.io/Mohamed-Ayman/full/OEYBQX',
          projectSource: 'https://codepen.io/Mohamed-Ayman/pen/OEYBQX',
          projectTime: '2020',
        },
        {
          projectImg: 'assets/img/projects/fileUpload.gif',
          projectTitle: 'File Upload ',
          projectSkills: 'HTML5, CSS3, JS',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'https://codepen.io/Mohamed-Ayman/full/Vdzoam',
          projectSource: 'https://codepen.io/Mohamed-Ayman/pen/Vdzoam',
          projectTime: '2020',
        },
        {
          projectImg: 'assets/img/projects/googleService.gif',
          projectTitle: 'Google Service',
          projectSkills: 'HTML5, CSS3, SCSS',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'https://codepen.io/Mohamed-Ayman/full/xzgLVW',
          projectSource: 'https://codepen.io/Mohamed-Ayman/pen/xzgLVW',
          projectTime: '2020',
        },
        {
          projectImg: 'assets/img/projects/choosePlan.gif',
          projectTitle: 'Choose Plan',
          projectSkills: 'HTML5, CSS3, JS',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'https://codepen.io/Mohamed-Ayman/full/gKvZMO',
          projectSource: 'https://codepen.io/Mohamed-Ayman/pen/gKvZMO',
          projectTime: '2020',
        },
        {
          projectImg: 'assets/img/projects/toDoList.gif',
          projectTitle: 'ToDo List',
          projectSkills: 'HTML5, CSS3, JS',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'https://codepen.io/Mohamed-Ayman/full/xzJKbj',
          projectSource: 'https://codepen.io/Mohamed-Ayman/pen/xzJKbj',
          projectTime: '2020',
        },
        {
          projectImg: 'assets/img/projects/textBackground.gif',
          projectTitle: 'text Background',
          projectSkills: 'HTML5, CSS3',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'https://codepen.io/Mohamed-Ayman/full/dyPbzMb',
          projectSource: 'https://codepen.io/Mohamed-Ayman/pen/dyPbzMb',
          projectTime: '2018',
        },
        {
          projectImg: 'assets/img/projects/trackiraAnimation.gif',
          projectTitle: 'Trackira Logo',
          projectSkills: 'HTML5, CSS3, Js',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'https://codepen.io/Mohamed-Ayman/full/rNaBGwO',
          projectSource: 'https://codepen.io/Mohamed-Ayman/pen/rNaBGwO',
          projectTime: '2019',
        },
        {
          projectImg: 'assets/img/projects/TennisBall.gif',
          projectTitle: 'Tennis Ball',
          projectSkills: 'HTML5, CSS3, Js',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'https://codepen.io/Mohamed-Ayman/full/ajzKXJ',
          projectSource: 'https://codepen.io/Mohamed-Ayman/pen/ajzKXJ',
          projectTime: '2018',
        },
        {
          projectImg: 'assets/img/projects/tiltEffect.PNG',
          projectTitle: 'Tilt Hover Effect',
          projectSkills: 'HTML5, CSS3, Js',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'https://codepen.io/Mohamed-Ayman/full/MXLvOV',
          projectSource: 'https://codepen.io/Mohamed-Ayman/pen/MXLvOV',
          projectTime: '2018',
        },
        {
          projectImg: 'assets/img/projects/newUploadFile.PNG',
          projectTitle: 'New Upload File',
          projectSkills: 'HTML5, CSS3',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'https://codepen.io/Mohamed-Ayman/full/BVrLzy',
          projectSource: 'https://codepen.io/Mohamed-Ayman/pen/BVrLzy',
          projectTime: '2018',
        },
        {
          projectImg: 'assets/img/projects/iceCream.gif',
          projectTitle: 'Taste Ice Cream',
          projectSkills: 'HTML5, CSS3, Js',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'https://codepen.io/Mohamed-Ayman/full/WygwEr',
          projectSource: 'https://codepen.io/Mohamed-Ayman/pen/WygwEr',
          projectTime: '2018',
        },
        {
          projectImg: 'assets/img/projects/Ribbons.PNG',
          projectTitle: 'Ribbons',
          projectSkills: 'HTML5, CSS3',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'https://codepen.io/Mohamed-Ayman/full/YLbmZW',
          projectSource: 'https://codepen.io/Mohamed-Ayman/pen/YLbmZW',
          projectTime: '2018',
        },
        {
          projectImg: 'assets/img/projects/ShopWithMe.PNG',
          projectTitle: 'Shop With Me',
          projectSkills: 'HTML5, CSS3',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'https://codepen.io/Mohamed-Ayman/full/gKYvbm',
          projectSource: 'https://codepen.io/Mohamed-Ayman/pen/gKYvbm',
          projectTime: '2018',
        },
        {
          projectImg: 'assets/img/projects/calendarPlan.PNG',
          projectTitle: 'Calendar Plan',
          projectSkills: 'HTML5, CSS3',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'https://codepen.io/Mohamed-Ayman/full/zjVyBy',
          projectSource: 'https://codepen.io/Mohamed-Ayman/pen/zjVyBy',
          projectTime: '2018',
        },
        {
          projectImg: 'assets/img/projects/Timer.PNG',
          projectTitle: 'Timer ',
          projectSkills: 'HTML5, CSS3',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'https://codepen.io/Mohamed-Ayman/full/jKxjeo',
          projectSource: 'https://codepen.io/Mohamed-Ayman/pen/jKxjeo',
          projectTime: '2018',
        },
        {
          projectImg: 'assets/img/projects/newChoosePlan.PNG',
          projectTitle: 'Timer ',
          projectSkills: 'HTML5, CSS3',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'https://codepen.io/Mohamed-Ayman/full/KeWjoY',
          projectSource: 'https://codepen.io/Mohamed-Ayman/pen/KeWjoY',
          projectTime: '2018',
        },

      ]
    },
    {

      name: 'Projects area',
      class: 'websites',
      subtitle: 'these were hard times ◕‸◕',
      footerContent: 'browsing all in github',
      areaProjects: [{
          projectImg: 'assets/img/projects/project-1.jpg',
          projectTitle: 'First Project',
          projectSkills: 'HTML5, CSS3, SASS/SCSS',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'live',
          projectSource: 'source',
          projectTime: '2020',
        },
        {
          projectImg: 'assets/img/projects/project-1.jpg',
          projectTitle: 'First Project',
          projectSkills: 'HTML5, CSS3, SASS/SCSS',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'live',
          projectSource: 'source',
          projectTime: '2020',
        },
        {
          projectImg: 'assets/img/projects/project-1.jpg',
          projectTitle: 'First Project',
          projectSkills: 'HTML5, CSS3, SASS/SCSS',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'live',
          projectSource: 'source',
          projectTime: '2020',
        },
        {
          projectImg: 'assets/img/projects/project-1.jpg',
          projectTitle: 'First Project',
          projectSkills: 'HTML5, CSS3, SASS/SCSS',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'live',
          projectSource: 'source',
          projectTime: '2020',
        },
      ]
    },
    {

      name: 'recent projects',
      class: 'recent',
      subtitle: 'selected ones',
      footerContent: 'browsing all in github',
      areaProjects: [{
          projectImg: 'assets/img/projects/project-1.jpg',
          projectTitle: 'First Project',
          projectSkills: 'HTML5, CSS3, SASS/SCSS',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'live',
          projectSource: 'source',
          projectTime: '2020',
        },
        {
          projectImg: 'assets/img/projects/project-1.jpg',
          projectTitle: 'First Project',
          projectSkills: 'HTML5, CSS3, SASS/SCSS',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'live',
          projectSource: 'source',
          projectTime: '2020',
        },
        {
          projectImg: 'assets/img/projects/project-1.jpg',
          projectTitle: 'First Project',
          projectSkills: 'HTML5, CSS3, SASS/SCSS',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'live',
          projectSource: 'source',
          projectTime: '2020',
        },

        {
          projectImg: 'assets/img/projects/project-1.jpg',
          projectTitle: 'First Project',
          projectSkills: 'HTML5, CSS3, SASS/SCSS',
          projectSummary: 'This work has been featured on CodePen ❤',
          projectLive: 'live',
          projectSource: 'source',
          projectTime: '2020',
        },
      ]
    },
  ]


  constructor() {}

  ngOnInit(): void {}

}
