import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-portfolio',
  templateUrl: './portfolio.component.html',
  styleUrls: ['./portfolio.component.css']
})
export class PortfolioComponent implements OnInit {
  portfolioParts = [
    {

      name: 'Styling area', 
      class:'styling',
      subtitle: 'daily practice',
      footerContent:'browsing all in github',
      areaProjects: [
        {projectImg: 'assets/img/projects/project-1.jpg',
         projectTitle: 'Services Section (Challenge)',
         projectSkills: 'HTML5, CSS3, SASS/SCSS',
         projectSummary: 'This work has been featured on CodePen ❤',
         projectLive: 'live',
         projectSource: 'source',
         projectTime: '2020',
        },
        {projectImg: 'assets/img/projects/project-1.jpg',
         projectTitle: 'Services Section (Challenge)',
         projectSkills: 'HTML5, CSS3, SASS/SCSS',
         projectSummary: 'This work has been featured on CodePen ❤',
         projectLive: 'live',
         projectSource: 'source',
         projectTime: '2020',
        },
        {projectImg: 'assets/img/projects/project-1.jpg',
         projectTitle: 'Services Section (Challenge)',
         projectSkills: 'HTML5, CSS3, SASS/SCSS',
         projectSummary: 'This work has been featured on CodePen ❤',
         projectLive: 'live',
         projectSource: 'source',
         projectTime: '2020',
        },
        {projectImg: 'assets/img/projects/project-1.jpg',
         projectTitle: 'Services Section (Challenge)',
         projectSkills: 'HTML5, CSS3, SASS/SCSS',
         projectSummary: 'This work has been featured on CodePen ❤',
         projectLive: 'live',
         projectSource: 'source',
         projectTime: '2020',
        },
        {projectImg: 'assets/img/projects/project-1.jpg',
         projectTitle: 'Services Section (Challenge)',
         projectSkills: 'HTML5, CSS3, SASS/SCSS',
         projectSummary: 'This work has been featured on CodePen ❤',
         projectLive: 'live',
         projectSource: 'source',
         projectTime: '2020',
        },
        {projectImg: 'assets/img/projects/project-1.jpg',
         projectTitle: 'Services Section (Challenge)',
         projectSkills: 'HTML5, CSS3, SASS/SCSS',
         projectSummary: 'This work has been featured on CodePen ❤',
         projectLive: 'live',
         projectSource: 'source',
         projectTime: '2020',
        },
        {projectImg: 'assets/img/projects/project-1.jpg',
         projectTitle: 'Services Section (Challenge)',
         projectSkills: 'HTML5, CSS3, SASS/SCSS',
         projectSummary: 'This work has been featured on CodePen ❤',
         projectLive: 'live',
         projectSource: 'source',
         projectTime: '2020',
        },
        {projectImg: 'assets/img/projects/project-1.jpg',
         projectTitle: 'Services Section (Challenge)',
         projectSkills: 'HTML5, CSS3, SASS/SCSS',
         projectSummary: 'This work has been featured on CodePen ❤',
         projectLive: 'live',
         projectSource: 'source',
         projectTime: '2020',
        },
        {projectImg: 'assets/img/projects/project-1.jpg',
         projectTitle: 'Services Section (Challenge)',
         projectSkills: 'HTML5, CSS3, SASS/SCSS',
         projectSummary: 'This work has been featured on CodePen ❤',
         projectLive: 'live',
         projectSource: 'source',
         projectTime: '2020',
        },
        {projectImg: 'assets/img/projects/project-1.jpg',
         projectTitle: 'Services Section (Challenge)',
         projectSkills: 'HTML5, CSS3, SASS/SCSS',
         projectSummary: 'This work has been featured on CodePen ❤',
         projectLive: 'live',
         projectSource: 'source',
         projectTime: '2020',
        },
        {projectImg: 'assets/img/projects/project-1.jpg',
         projectTitle: 'Services Section (Challenge)',
         projectSkills: 'HTML5, CSS3, SASS/SCSS',
         projectSummary: 'This work has been featured on CodePen ❤',
         projectLive: 'live',
         projectSource: 'source',
         projectTime: '2020',
        },
        {projectImg: 'assets/img/projects/project-1.jpg',
         projectTitle: 'Services Section (Challenge)',
         projectSkills: 'HTML5, CSS3, SASS/SCSS',
         projectSummary: 'This work has been featured on CodePen ❤',
         projectLive: 'live',
         projectSource: 'source',
         projectTime: '2020',
        },
        {projectImg: 'assets/img/projects/project-1.jpg',
         projectTitle: 'Services Section (Challenge)',
         projectSkills: 'HTML5, CSS3, SASS/SCSS',
         projectSummary: 'This work has been featured on CodePen ❤',
         projectLive: 'live',
         projectSource: 'source',
         projectTime: '2020',
        },
      ]
    },
    {

      name: 'Projects area', 
      class:'websites',
      subtitle: 'daily practice',
      footerContent:'browsing all in github',
      areaProjects: [
        {projectImg: 'assets/img/projects/project-1.jpg',
         projectTitle: 'First Project',
         projectSkills: 'HTML5, CSS3, SASS/SCSS',
         projectSummary: 'This work has been featured on CodePen ❤',
         projectLive: 'live',
         projectSource: 'source',
         projectTime: '2020',
        }
      ]
    },
    {

      name: 'recent projects', 
      class:'recent',
      subtitle: 'daily practice',
      footerContent:'browsing all in github',
      areaProjects: [
        {projectImg: 'assets/img/projects/project-1.jpg',
         projectTitle: 'First Project',
         projectSkills: 'HTML5, CSS3, SASS/SCSS',
         projectSummary: 'This work has been featured on CodePen ❤',
         projectLive: 'live',
         projectSource: 'source',
         projectTime: '2020',
        }
      ]
    },
  ]


  portfolioProjects = [
    {imgSrc: 'assets/img/projects/project-1.jpg', projectName: 'Image Project'},
    {imgSrc: 'assets/img/projects/project-2.jpg', projectName: 'Image Project'},
    {imgSrc: 'assets/img/projects/project-3.jpg', projectName: 'Image Project'},
    {imgSrc: 'assets/img/projects/project-4.jpg', projectName: 'Image Project'},
    {imgSrc: 'assets/img/projects/project-5.jpg', projectName: 'Image Project'},
    {imgSrc: 'assets/img/projects/project-6.jpg', projectName: 'Image Project'},
    {imgSrc: 'assets/img/projects/project-7.jpg', projectName: 'Image Project'},
    {imgSrc: 'assets/img/projects/project-8.jpg', projectName: 'Image Project'},
    {imgSrc: 'assets/img/projects/project-9.jpg', projectName: 'Image Project'}
  ]
  constructor() { }

  ngOnInit(): void {
  }

}
